repos:
  - repo: local
    hooks:
      - id: common_language
        name: common_language
        language: system
        entry: common_language
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
        #args: [--britishise]
